import Head from "next/head"

import { Layout } from "@components/layout/Layout"

function Home() {
  const strArr = ["apple", "banana", "peach", "orange", "melon"]
  const numArr = [1, 2, 34, 4, 7, 2, 43, 4, 7, 8, 9, 1, 56, 3, 2]

  // Оставляем только не повторяющиеся цифры
  let newNumArr = numArr.filter((number, index) => {
    return numArr.indexOf(number) === index
  })

  // Создайте функцию unique(arr), которая вернёт массив уникальных, не повторяющихся значений массива arr.
  function unique(arr) {
    return Array.from(new Set(arr))
  }

  // Сортируем цифры в порядке возрастания
  numArr.sort((a, b) => a - b)

  // Сумма всех чисел
  let total = numArr.reduce((sum, number) => {
    return sum + number
  }, 0)

  // Сумма свойств объекта
  let salaries = {
    John: 100,
    Pete: 300,
  }
  function sumSalaries(salaries) {
    return Object.values(salaries).reduce((a, b) => a + b, 0) // 400
  }

  // Создадим объект и присвоим всем элементам значение
  let fruits = strArr.reduce((acc, element) => {
    acc[element] = 1
    return acc
  }, {})

  // Делаем первую букву заглавной
  const camelize = (str) => {
    return str
      .split(" ")
      .map((word) => word[0].toUpperCase() + word.slice(1))
      .join(" ")
  }

  // Нужно получить отсортированную копию, но оставить arr неизмененным.
  const copySorted = (arr) => {
    return arr.slice().sort()
  }

  // Напишите функцию reverse, которая принимает в себя строку и возвращает эту строку в обратном порядке.
  const someString = "This is some strange string"
  function reverse(str) {
    return str.split("").reverse().join("")
  }

  // Числа Фибоначчи
  function fib(n) {
    let a = 1
    let b = 1
    for (let i = 3; i <= n; i++) {
      let c = a + b
      a = b
      b = c
    }
    return b
  } // или с помощью рекурсии, но такое решение будет работать долго.

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <h1 className="title">Best of the best</h1>
        <p className="desc">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora eius, repellat fugiat
          obcaecati hic ipsum nam quasi? Aliquid, porro commodi laboriosam molestiae veniam, numquam
          sapiente laudantium natus placeat eius veritatis.Lorem ipsum dolor sit amet consectetur
          adipisicing elit.
        </p>
      </Layout>
    </>
  )
}

export default Home
